"""Initial models migration

Revision ID: 0babbe5d3bd8
Revises: 
Create Date: 2026-09-28 15:41:21.486571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0babbe5d3bd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # The app historically created its schema with db.create_all() at startup,
    # so the database may already hold these tables. In that case this baseline
    # migration is a no-op and Alembic simply records the revision.
    if sa.inspect(op.get_bind()).has_table("users"):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id_hash', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guest_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guest_sessions_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_guest_sessions_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_guest_sessions_session_id_hash'), ['session_id_hash'], unique=True)

    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_service_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rate_usd_per_1000', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('min_qty', sa.Integer(), nullable=False),
    sa.Column('max_qty', sa.Integer(), nullable=False),
    sa.Column('refill_available', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_provider_service_id'), ['provider_service_id'], unique=True)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_user_id', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('notification_prefs_raw', sa.Text(), nullable=False),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_public_user_id'), ['public_user_id'], unique=True)

    op.create_table('admin_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_actions_admin_id'), ['admin_id'], unique=False)

    op.create_table('ledger_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('amount_ghs', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('balance_before', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount_ghs >= 0', name='chk_ledger_amount_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_transactions_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_transactions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_order_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=150), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('charge_ghs', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider_order_id', sa.Integer(), nullable=True),
    sa.Column('provider_status_raw', sa.String(length=50), nullable=True),
    sa.Column('provider_charge', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('needs_attention', sa.Boolean(), nullable=False),
    sa.Column('start_count', sa.Integer(), nullable=True),
    sa.Column('remains', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_provider_order_id'), ['provider_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_public_order_id'), ['public_order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('network', sa.String(length=20), nullable=False),
    sa.Column('amount_ghs', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('screenshot_filename', sa.String(length=255), nullable=True),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_payment_id'), ['payment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_transaction_reference'), ['transaction_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('order_id_ref', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_tickets_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_ticket_id'), ['ticket_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_support_tickets_user_id'), ['user_id'], unique=False)

    op.create_table('fraud_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fraud_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fraud_flags_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fraud_flags_user_id'), ['user_id'], unique=False)

    op.create_table('order_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_events_order_id'), ['order_id'], unique=False)

    op.create_table('payment_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('raw_ai_json_str', sa.Text(), nullable=True),
    sa.Column('checks_passed_str', sa.Text(), nullable=True),
    sa.Column('checks_failed_str', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_verifications_payment_id'), ['payment_id'], unique=False)

    op.create_table('refills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('provider_refill_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refills_order_id'), ['order_id'], unique=False)

    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount_ghs', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refunds_order_id'), ['order_id'], unique=False)

    op.create_table('support_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('sender_role', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_messages_ticket_id'), ['ticket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_messages_ticket_id'))

    op.drop_table('support_messages')
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refunds_order_id'))

    op.drop_table('refunds')
    with op.batch_alter_table('refills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refills_order_id'))

    op.drop_table('refills')
    with op.batch_alter_table('payment_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_verifications_payment_id'))

    op.drop_table('payment_verifications')
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_events_order_id'))

    op.drop_table('order_events')
    with op.batch_alter_table('fraud_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fraud_flags_user_id'))
        batch_op.drop_index(batch_op.f('ix_fraud_flags_payment_id'))

    op.drop_table('fraud_flags')
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_tickets_user_id'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_session_id'))

    op.drop_table('support_tickets')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_transaction_reference'))
        batch_op.drop_index(batch_op.f('ix_payments_session_id'))
        batch_op.drop_index(batch_op.f('ix_payments_payment_id'))

    op.drop_table('payments')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_session_id'))
        batch_op.drop_index(batch_op.f('ix_orders_public_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_provider_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_idempotency_key'))

    op.drop_table('orders')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_session_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('ledger_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_transactions_session_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_transactions_reference'))

    op.drop_table('ledger_transactions')
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_actions_admin_id'))

    op.drop_table('admin_actions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_public_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_key'))

    op.drop_table('settings')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_provider_service_id'))
        batch_op.drop_index(batch_op.f('ix_services_platform'))

    op.drop_table('services')
    op.drop_table('platforms')
    with op.batch_alter_table('guest_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_sessions_session_id_hash'))
        batch_op.drop_index(batch_op.f('ix_guest_sessions_phone'))
        batch_op.drop_index(batch_op.f('ix_guest_sessions_email'))

    op.drop_table('guest_sessions')
    # ### end Alembic commands ###
