from typing import Protocol, Optional, Any, Tuple
from backend.app.providers.provider_client import ProviderService, ProviderOrderStatus, ProviderError

class ProviderInterface(Protocol):
    def get_services(self) -> list[ProviderService]: ...
    def create_order(
        self,
        *,
        service_id: int,
        link: str,
        quantity: int,
        runs: Optional[int] = None,
        interval: Optional[int] = None,
    ) -> int: ...
    def get_order_status(self, provider_order_id: int) -> ProviderOrderStatus: ...
    def get_multiple_order_status(
        self, provider_order_ids: list[int]
    ) -> dict[int, ProviderOrderStatus | ProviderError]: ...
    def request_refill(self, provider_order_id: int) -> str: ...
    def get_refill_status(self, refill_id: str) -> str: ...
    def cancel_order(self, provider_order_id: int) -> bool: ...
    def get_provider_balance(self) -> Tuple[float, str]: ...
    def test_provider_connection(self) -> dict[str, Any]: ...
    def check_provider_health(self) -> dict[str, Any]: ...
